# Version of docker-compose syntax
version: "3.9"

# Services needed for the project
services:
  # Backend service
  backend:
    # Build configurations
    build:
      # Path to Dockerfile to build the image
      context: ./backend
      # Run as development environment
      args:
        - DEV=true
    # Map local port 8000 to container port 8000
    ports:
      - "8000:8000"
    # Sync app local directory to container directory
    volumes:
      - ./app:/app
    # Default command starts the server
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
