# Generated by Django 4.1.9 on 2023-06-15 04:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_resource_topic_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='link',
            field=models.URLField(max_length=255, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
    ]
