# Generated by Django 4.1.9 on 2023-06-16 07:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_question_topic_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='wrong_answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=[], size=None),
        ),
    ]
