---
name: Backend Tests

on:
  push:
    # Run the workflow on push events to the main branch
    branches:
      - main
    # Exclude the frontend and proxy from triggering the workflow
    paths-ignore:
      - 'frontend/**'
      - 'proxy/**'

jobs:
  test-lint:
    name: Test and Lint
    # OS to run the job on
    runs-on: ubuntu-20.04 
    steps:
      # Authenticate with Docker Hub to bypass the 
      # Github shared rate limit for pulling images
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          # Token generated in Docker Hub
          # Stored in GitHub Secrets
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Checkout the code from the repo
      - name: Checkout
        uses: actions/checkout@v2
      # Run unit tests
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      # Run linting
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
